
// PARÂMETROS OPCIONAIS (n1=0, n2=0) => SE QUALQUER UM DELES NÃO FOR PASSADO, JÁ ESTÁ PRÉ-DEFINIDO O QUE O JS DEVE CONSIDERAR NA EXECUÇÃO DO PROGRAMA
function soma(n1=0, n2=0) {
   return n1 + n2
}

console.log(soma(2))
